package com.yimayhd.erpcenter.dal.sales.client.sales.po;

public class AssistantSupplierImg {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_supplier_img.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_supplier_img.img_id
	 * @mbggenerated
	 */
	private Integer imgId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_supplier_img.imgtype_id
	 * @mbggenerated
	 */
	private Integer imgtypeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_supplier_img.img_name
	 * @mbggenerated
	 */
	private String imgName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_supplier_img.img_path
	 * @mbggenerated
	 */
	private String imgPath;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_supplier_img.id
	 * @return  the value of assistant_supplier_img.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_supplier_img.id
	 * @param id  the value for assistant_supplier_img.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_supplier_img.img_id
	 * @return  the value of assistant_supplier_img.img_id
	 * @mbggenerated
	 */
	public Integer getImgId() {
		return imgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_supplier_img.img_id
	 * @param imgId  the value for assistant_supplier_img.img_id
	 * @mbggenerated
	 */
	public void setImgId(Integer imgId) {
		this.imgId = imgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_supplier_img.imgtype_id
	 * @return  the value of assistant_supplier_img.imgtype_id
	 * @mbggenerated
	 */
	public Integer getImgtypeId() {
		return imgtypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_supplier_img.imgtype_id
	 * @param imgtypeId  the value for assistant_supplier_img.imgtype_id
	 * @mbggenerated
	 */
	public void setImgtypeId(Integer imgtypeId) {
		this.imgtypeId = imgtypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_supplier_img.img_name
	 * @return  the value of assistant_supplier_img.img_name
	 * @mbggenerated
	 */
	public String getImgName() {
		return imgName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_supplier_img.img_name
	 * @param imgName  the value for assistant_supplier_img.img_name
	 * @mbggenerated
	 */
	public void setImgName(String imgName) {
		this.imgName = imgName == null ? null : imgName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_supplier_img.img_path
	 * @return  the value of assistant_supplier_img.img_path
	 * @mbggenerated
	 */
	public String getImgPath() {
		return imgPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_supplier_img.img_path
	 * @param imgPath  the value for assistant_supplier_img.img_path
	 * @mbggenerated
	 */
	public void setImgPath(String imgPath) {
		this.imgPath = imgPath == null ? null : imgPath.trim();
	}
}