package com.yimayhd.erpcenter.dal.sales.client.sales.po;

import java.io.Serializable;
import java.util.Date;

public class AssistantGroupOrder implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = -2346449325686970674L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_group_order.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_group_order.order_id
	 * @mbggenerated
	 */
	private Integer orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_group_order.biz_id
	 * @mbggenerated
	 */
	private Integer bizId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_group_order.group_id
	 * @mbggenerated
	 */
	private Integer groupId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_group_order.order_type
	 * @mbggenerated
	 */
	private Integer orderType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_group_order.supplier_name
	 * @mbggenerated
	 */
	private String supplierName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_group_order.contact_name
	 * @mbggenerated
	 */
	private String contactName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_group_order.contact_tel
	 * @mbggenerated
	 */
	private String contactTel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_group_order.contact_mobile
	 * @mbggenerated
	 */
	private String contactMobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_group_order.sale_operator_name
	 * @mbggenerated
	 */
	private String saleOperatorName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_group_order.num_adult
	 * @mbggenerated
	 */
	private Integer numAdult;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_group_order.num_child
	 * @mbggenerated
	 */
	private Integer numChild;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_group_order.num_guide
	 * @mbggenerated
	 */
	private Integer numGuide;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_group_order.departure_date
	 * @mbggenerated
	 */
	private String departureDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_group_order.product_brand_name
	 * @mbggenerated
	 */
	private String productBrandName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_group_order.product_name
	 * @mbggenerated
	 */
	private String productName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_group_order.receive_mode
	 * @mbggenerated
	 */
	private String receiveMode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_group_order.state
	 * @mbggenerated
	 */
	private Integer state;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_group_order.province_name
	 * @mbggenerated
	 */
	private String provinceName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_group_order.city_name
	 * @mbggenerated
	 */
	private String cityName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_group_order.id
	 * @return  the value of assistant_group_order.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_group_order.id
	 * @param id  the value for assistant_group_order.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_group_order.order_id
	 * @return  the value of assistant_group_order.order_id
	 * @mbggenerated
	 */
	public Integer getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_group_order.order_id
	 * @param orderId  the value for assistant_group_order.order_id
	 * @mbggenerated
	 */
	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_group_order.biz_id
	 * @return  the value of assistant_group_order.biz_id
	 * @mbggenerated
	 */
	public Integer getBizId() {
		return bizId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_group_order.biz_id
	 * @param bizId  the value for assistant_group_order.biz_id
	 * @mbggenerated
	 */
	public void setBizId(Integer bizId) {
		this.bizId = bizId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_group_order.group_id
	 * @return  the value of assistant_group_order.group_id
	 * @mbggenerated
	 */
	public Integer getGroupId() {
		return groupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_group_order.group_id
	 * @param groupId  the value for assistant_group_order.group_id
	 * @mbggenerated
	 */
	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_group_order.order_type
	 * @return  the value of assistant_group_order.order_type
	 * @mbggenerated
	 */
	public Integer getOrderType() {
		return orderType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_group_order.order_type
	 * @param orderType  the value for assistant_group_order.order_type
	 * @mbggenerated
	 */
	public void setOrderType(Integer orderType) {
		this.orderType = orderType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_group_order.supplier_name
	 * @return  the value of assistant_group_order.supplier_name
	 * @mbggenerated
	 */
	public String getSupplierName() {
		return supplierName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_group_order.supplier_name
	 * @param supplierName  the value for assistant_group_order.supplier_name
	 * @mbggenerated
	 */
	public void setSupplierName(String supplierName) {
		this.supplierName = supplierName == null ? null : supplierName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_group_order.contact_name
	 * @return  the value of assistant_group_order.contact_name
	 * @mbggenerated
	 */
	public String getContactName() {
		return contactName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_group_order.contact_name
	 * @param contactName  the value for assistant_group_order.contact_name
	 * @mbggenerated
	 */
	public void setContactName(String contactName) {
		this.contactName = contactName == null ? null : contactName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_group_order.contact_tel
	 * @return  the value of assistant_group_order.contact_tel
	 * @mbggenerated
	 */
	public String getContactTel() {
		return contactTel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_group_order.contact_tel
	 * @param contactTel  the value for assistant_group_order.contact_tel
	 * @mbggenerated
	 */
	public void setContactTel(String contactTel) {
		this.contactTel = contactTel == null ? null : contactTel.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_group_order.contact_mobile
	 * @return  the value of assistant_group_order.contact_mobile
	 * @mbggenerated
	 */
	public String getContactMobile() {
		return contactMobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_group_order.contact_mobile
	 * @param contactMobile  the value for assistant_group_order.contact_mobile
	 * @mbggenerated
	 */
	public void setContactMobile(String contactMobile) {
		this.contactMobile = contactMobile == null ? null : contactMobile.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_group_order.sale_operator_name
	 * @return  the value of assistant_group_order.sale_operator_name
	 * @mbggenerated
	 */
	public String getSaleOperatorName() {
		return saleOperatorName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_group_order.sale_operator_name
	 * @param saleOperatorName  the value for assistant_group_order.sale_operator_name
	 * @mbggenerated
	 */
	public void setSaleOperatorName(String saleOperatorName) {
		this.saleOperatorName = saleOperatorName == null ? null : saleOperatorName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_group_order.num_adult
	 * @return  the value of assistant_group_order.num_adult
	 * @mbggenerated
	 */
	public Integer getNumAdult() {
		return numAdult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_group_order.num_adult
	 * @param numAdult  the value for assistant_group_order.num_adult
	 * @mbggenerated
	 */
	public void setNumAdult(Integer numAdult) {
		this.numAdult = numAdult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_group_order.num_child
	 * @return  the value of assistant_group_order.num_child
	 * @mbggenerated
	 */
	public Integer getNumChild() {
		return numChild;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_group_order.num_child
	 * @param numChild  the value for assistant_group_order.num_child
	 * @mbggenerated
	 */
	public void setNumChild(Integer numChild) {
		this.numChild = numChild;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_group_order.num_guide
	 * @return  the value of assistant_group_order.num_guide
	 * @mbggenerated
	 */
	public Integer getNumGuide() {
		return numGuide;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_group_order.num_guide
	 * @param numGuide  the value for assistant_group_order.num_guide
	 * @mbggenerated
	 */
	public void setNumGuide(Integer numGuide) {
		this.numGuide = numGuide;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_group_order.departure_date
	 * @return  the value of assistant_group_order.departure_date
	 * @mbggenerated
	 */
	public String getDepartureDate() {
		return departureDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_group_order.departure_date
	 * @param departureDate  the value for assistant_group_order.departure_date
	 * @mbggenerated
	 */
	public void setDepartureDate(String departureDate) {
		this.departureDate = departureDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_group_order.product_brand_name
	 * @return  the value of assistant_group_order.product_brand_name
	 * @mbggenerated
	 */
	public String getProductBrandName() {
		return productBrandName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_group_order.product_brand_name
	 * @param productBrandName  the value for assistant_group_order.product_brand_name
	 * @mbggenerated
	 */
	public void setProductBrandName(String productBrandName) {
		this.productBrandName = productBrandName == null ? null : productBrandName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_group_order.product_name
	 * @return  the value of assistant_group_order.product_name
	 * @mbggenerated
	 */
	public String getProductName() {
		return productName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_group_order.product_name
	 * @param productName  the value for assistant_group_order.product_name
	 * @mbggenerated
	 */
	public void setProductName(String productName) {
		this.productName = productName == null ? null : productName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_group_order.receive_mode
	 * @return  the value of assistant_group_order.receive_mode
	 * @mbggenerated
	 */
	public String getReceiveMode() {
		return receiveMode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_group_order.receive_mode
	 * @param receiveMode  the value for assistant_group_order.receive_mode
	 * @mbggenerated
	 */
	public void setReceiveMode(String receiveMode) {
		this.receiveMode = receiveMode == null ? null : receiveMode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_group_order.state
	 * @return  the value of assistant_group_order.state
	 * @mbggenerated
	 */
	public Integer getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_group_order.state
	 * @param state  the value for assistant_group_order.state
	 * @mbggenerated
	 */
	public void setState(Integer state) {
		this.state = state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_group_order.province_name
	 * @return  the value of assistant_group_order.province_name
	 * @mbggenerated
	 */
	public String getProvinceName() {
		return provinceName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_group_order.province_name
	 * @param provinceName  the value for assistant_group_order.province_name
	 * @mbggenerated
	 */
	public void setProvinceName(String provinceName) {
		this.provinceName = provinceName == null ? null : provinceName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_group_order.city_name
	 * @return  the value of assistant_group_order.city_name
	 * @mbggenerated
	 */
	public String getCityName() {
		return cityName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_group_order.city_name
	 * @param cityName  the value for assistant_group_order.city_name
	 * @mbggenerated
	 */
	public void setCityName(String cityName) {
		this.cityName = cityName == null ? null : cityName.trim();
	}
}