package com.yimayhd.erpcenter.dal.sales.client.sales.po;

import java.io.Serializable;
import java.util.Date;

public class AssistantGroupOrderTransport  implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = -5276224438476237903L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_group_order_transport.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_group_order_transport.order_id
	 * @mbggenerated
	 */
	private Integer orderId;
	private Integer groupId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_group_order_transport.class_no
	 * @mbggenerated
	 */
	private Integer trans_type;
	private String classNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_group_order_transport.departure_city
	 * @mbggenerated
	 */
	private String departureCity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_group_order_transport.departure_date
	 * @mbggenerated
	 */
	private String departureDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_group_order_transport.departure_time
	 * @mbggenerated
	 */
	private String departureTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_group_order_transport.arrival_city
	 * @mbggenerated
	 */
	private String arrivalCity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_group_order_transport.arrival_date
	 * @mbggenerated
	 */
	private String arrivalDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_group_order_transport.arrival_time
	 * @mbggenerated
	 */
	private String arrivalTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_group_order_transport.id
	 * @return  the value of assistant_group_order_transport.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_group_order_transport.id
	 * @param id  the value for assistant_group_order_transport.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_group_order_transport.order_id
	 * @return  the value of assistant_group_order_transport.order_id
	 * @mbggenerated
	 */
	public Integer getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_group_order_transport.order_id
	 * @param orderId  the value for assistant_group_order_transport.order_id
	 * @mbggenerated
	 */
	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	public Integer getGroupId() {
		return groupId;
	}
	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_group_order_transport.class_no
	 * @return  the value of assistant_group_order_transport.class_no
	 * @mbggenerated
	 */
	public String getClassNo() {
		return classNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_group_order_transport.class_no
	 * @param classNo  the value for assistant_group_order_transport.class_no
	 * @mbggenerated
	 */
	public void setClassNo(String classNo) {
		this.classNo = classNo == null ? null : classNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_group_order_transport.departure_city
	 * @return  the value of assistant_group_order_transport.departure_city
	 * @mbggenerated
	 */
	public String getDepartureCity() {
		return departureCity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_group_order_transport.departure_city
	 * @param departureCity  the value for assistant_group_order_transport.departure_city
	 * @mbggenerated
	 */
	public void setDepartureCity(String departureCity) {
		this.departureCity = departureCity == null ? null : departureCity.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_group_order_transport.departure_date
	 * @return  the value of assistant_group_order_transport.departure_date
	 * @mbggenerated
	 */
	public String getDepartureDate() {
		return departureDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_group_order_transport.departure_date
	 * @param departureDate  the value for assistant_group_order_transport.departure_date
	 * @mbggenerated
	 */
	public void setDepartureDate(String departureDate) {
		this.departureDate = departureDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_group_order_transport.departure_time
	 * @return  the value of assistant_group_order_transport.departure_time
	 * @mbggenerated
	 */
	public String getDepartureTime() {
		return departureTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_group_order_transport.departure_time
	 * @param departureTime  the value for assistant_group_order_transport.departure_time
	 * @mbggenerated
	 */
	public void setDepartureTime(String departureTime) {
		this.departureTime = departureTime == null ? null : departureTime.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_group_order_transport.arrival_city
	 * @return  the value of assistant_group_order_transport.arrival_city
	 * @mbggenerated
	 */
	public String getArrivalCity() {
		return arrivalCity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_group_order_transport.arrival_city
	 * @param arrivalCity  the value for assistant_group_order_transport.arrival_city
	 * @mbggenerated
	 */
	public void setArrivalCity(String arrivalCity) {
		this.arrivalCity = arrivalCity == null ? null : arrivalCity.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_group_order_transport.arrival_date
	 * @return  the value of assistant_group_order_transport.arrival_date
	 * @mbggenerated
	 */
	public String getArrivalDate() {
		return arrivalDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_group_order_transport.arrival_date
	 * @param arrivalDate  the value for assistant_group_order_transport.arrival_date
	 * @mbggenerated
	 */
	public void setArrivalDate(String arrivalDate) {
		this.arrivalDate = arrivalDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_group_order_transport.arrival_time
	 * @return  the value of assistant_group_order_transport.arrival_time
	 * @mbggenerated
	 */
	public String getArrivalTime() {
		return arrivalTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_group_order_transport.arrival_time
	 * @param arrivalTime  the value for assistant_group_order_transport.arrival_time
	 * @mbggenerated
	 */
	public void setArrivalTime(String arrivalTime) {
		this.arrivalTime = arrivalTime == null ? null : arrivalTime.trim();
	}

	public Integer getTrans_type() {
		return trans_type;
	}

	public void setTrans_type(Integer trans_type) {
		this.trans_type = trans_type;
	}
}