package com.yimayhd.erpcenter.dal.sales.client.sales.po;

import java.io.Serializable;

public class AssistantGroupRouteSupplier  implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = -1132600489163108255L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_group_route_supplier.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_group_route_supplier.route_id
	 * @mbggenerated
	 */
	private Integer routeId;
	private Integer groupId;
	private Integer orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_group_route_supplier.supplier_type
	 * @mbggenerated
	 */
	private Integer supplierType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_group_route_supplier.supplier_id
	 * @mbggenerated
	 */
	private Integer supplierId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_group_route_supplier.supplier_name
	 * @mbggenerated
	 */
	private String supplierName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_group_route_supplier.id
	 * @return  the value of assistant_group_route_supplier.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_group_route_supplier.id
	 * @param id  the value for assistant_group_route_supplier.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_group_route_supplier.route_id
	 * @return  the value of assistant_group_route_supplier.route_id
	 * @mbggenerated
	 */
	public Integer getRouteId() {
		return routeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_group_route_supplier.route_id
	 * @param routeId  the value for assistant_group_route_supplier.route_id
	 * @mbggenerated
	 */
	public void setRouteId(Integer routeId) {
		this.routeId = routeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_group_route_supplier.supplier_type
	 * @return  the value of assistant_group_route_supplier.supplier_type
	 * @mbggenerated
	 */
	public Integer getSupplierType() {
		return supplierType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_group_route_supplier.supplier_type
	 * @param supplierType  the value for assistant_group_route_supplier.supplier_type
	 * @mbggenerated
	 */
	public void setSupplierType(Integer supplierType) {
		this.supplierType = supplierType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_group_route_supplier.supplier_id
	 * @return  the value of assistant_group_route_supplier.supplier_id
	 * @mbggenerated
	 */
	public Integer getSupplierId() {
		return supplierId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_group_route_supplier.supplier_id
	 * @param supplierId  the value for assistant_group_route_supplier.supplier_id
	 * @mbggenerated
	 */
	public void setSupplierId(Integer supplierId) {
		this.supplierId = supplierId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_group_route_supplier.supplier_name
	 * @return  the value of assistant_group_route_supplier.supplier_name
	 * @mbggenerated
	 */
	public String getSupplierName() {
		return supplierName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_group_route_supplier.supplier_name
	 * @param supplierName  the value for assistant_group_route_supplier.supplier_name
	 * @mbggenerated
	 */
	public void setSupplierName(String supplierName) {
		this.supplierName = supplierName == null ? null : supplierName.trim();
	}

	public Integer getGroupId() {
		return groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	public Integer getOrderId() {
		return orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}
}