package com.yimayhd.erpcenter.dal.sales.client.sales.po;

import java.io.Serializable;
import java.util.Date;

public class AssistantGroup implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 5897590166164296386L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_group.id
	 * @mbggenerated
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_group.group_id
	 * @mbggenerated
	 */
	private Integer groupId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_group.biz_id
	 * @mbggenerated
	 */
	private Integer bizId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_group.group_mode
	 * @mbggenerated
	 */
	private Integer groupMode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_group.group_code
	 * @mbggenerated
	 */
	private String groupCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_group.product_brand_name
	 * @mbggenerated
	 */
	private String productBrandName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_group.product_name
	 * @mbggenerated
	 */
	private String productName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_group.daynum
	 * @mbggenerated
	 */
	private Integer daynum;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_group.date_start
	 * @mbggenerated
	 */
	private String dateStart;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_group.date_end
	 * @mbggenerated
	 */
	private String dateEnd;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_group.total_adult
	 * @mbggenerated
	 */
	private Integer totalAdult;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_group.total_child
	 * @mbggenerated
	 */
	private Integer totalChild;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_group.total_guide
	 * @mbggenerated
	 */
	private Integer totalGuide;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_group.operator_name
	 * @mbggenerated
	 */
	private String operatorName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_group.update_state
	 * @mbggenerated
	 */
	private Integer updateState;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_group.update_time
	 * @mbggenerated
	 */
	private String updateTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_group.warm_notice
	 * @mbggenerated
	 */
	private String warmNotice;



	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_group.id
	 * @return  the value of assistant_group.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_group.id
	 * @param id  the value for assistant_group.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_group.group_id
	 * @return  the value of assistant_group.group_id
	 * @mbggenerated
	 */
	public Integer getGroupId() {
		return groupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_group.group_id
	 * @param groupId  the value for assistant_group.group_id
	 * @mbggenerated
	 */
	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_group.biz_id
	 * @return  the value of assistant_group.biz_id
	 * @mbggenerated
	 */
	public Integer getBizId() {
		return bizId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_group.biz_id
	 * @param bizId  the value for assistant_group.biz_id
	 * @mbggenerated
	 */
	public void setBizId(Integer bizId) {
		this.bizId = bizId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_group.group_mode
	 * @return  the value of assistant_group.group_mode
	 * @mbggenerated
	 */
	public Integer getGroupMode() {
		return groupMode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_group.group_mode
	 * @param groupMode  the value for assistant_group.group_mode
	 * @mbggenerated
	 */
	public void setGroupMode(Integer groupMode) {
		this.groupMode = groupMode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_group.group_code
	 * @return  the value of assistant_group.group_code
	 * @mbggenerated
	 */
	public String getGroupCode() {
		return groupCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_group.group_code
	 * @param groupCode  the value for assistant_group.group_code
	 * @mbggenerated
	 */
	public void setGroupCode(String groupCode) {
		this.groupCode = groupCode == null ? null : groupCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_group.product_brand_name
	 * @return  the value of assistant_group.product_brand_name
	 * @mbggenerated
	 */
	public String getProductBrandName() {
		return productBrandName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_group.product_brand_name
	 * @param productBrandName  the value for assistant_group.product_brand_name
	 * @mbggenerated
	 */
	public void setProductBrandName(String productBrandName) {
		this.productBrandName = productBrandName == null ? null : productBrandName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_group.product_name
	 * @return  the value of assistant_group.product_name
	 * @mbggenerated
	 */
	public String getProductName() {
		return productName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_group.product_name
	 * @param productName  the value for assistant_group.product_name
	 * @mbggenerated
	 */
	public void setProductName(String productName) {
		this.productName = productName == null ? null : productName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_group.daynum
	 * @return  the value of assistant_group.daynum
	 * @mbggenerated
	 */
	public Integer getDaynum() {
		return daynum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_group.daynum
	 * @param daynum  the value for assistant_group.daynum
	 * @mbggenerated
	 */
	public void setDaynum(Integer daynum) {
		this.daynum = daynum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_group.date_start
	 * @return  the value of assistant_group.date_start
	 * @mbggenerated
	 */
	public String getDateStart() {
		return dateStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_group.date_start
	 * @param dateStart  the value for assistant_group.date_start
	 * @mbggenerated
	 */
	public void setDateStart(String dateStart) {
		this.dateStart = dateStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_group.date_end
	 * @return  the value of assistant_group.date_end
	 * @mbggenerated
	 */
	public String getDateEnd() {
		return dateEnd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_group.date_end
	 * @param dateEnd  the value for assistant_group.date_end
	 * @mbggenerated
	 */
	public void setDateEnd(String dateEnd) {
		this.dateEnd = dateEnd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_group.total_adult
	 * @return  the value of assistant_group.total_adult
	 * @mbggenerated
	 */
	public Integer getTotalAdult() {
		return totalAdult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_group.total_adult
	 * @param totalAdult  the value for assistant_group.total_adult
	 * @mbggenerated
	 */
	public void setTotalAdult(Integer totalAdult) {
		this.totalAdult = totalAdult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_group.total_child
	 * @return  the value of assistant_group.total_child
	 * @mbggenerated
	 */
	public Integer getTotalChild() {
		return totalChild;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_group.total_child
	 * @param totalChild  the value for assistant_group.total_child
	 * @mbggenerated
	 */
	public void setTotalChild(Integer totalChild) {
		this.totalChild = totalChild;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_group.total_guide
	 * @return  the value of assistant_group.total_guide
	 * @mbggenerated
	 */
	public Integer getTotalGuide() {
		return totalGuide;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_group.total_guide
	 * @param totalGuide  the value for assistant_group.total_guide
	 * @mbggenerated
	 */
	public void setTotalGuide(Integer totalGuide) {
		this.totalGuide = totalGuide;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_group.operator_name
	 * @return  the value of assistant_group.operator_name
	 * @mbggenerated
	 */
	public String getOperatorName() {
		return operatorName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_group.operator_name
	 * @param operatorName  the value for assistant_group.operator_name
	 * @mbggenerated
	 */
	public void setOperatorName(String operatorName) {
		this.operatorName = operatorName == null ? null : operatorName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_group.update_state
	 * @return  the value of assistant_group.update_state
	 * @mbggenerated
	 */
	public Integer getUpdateState() {
		return updateState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_group.update_state
	 * @param updateState  the value for assistant_group.update_state
	 * @mbggenerated
	 */
	public void setUpdateState(Integer updateState) {
		this.updateState = updateState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_group.update_time
	 * @return  the value of assistant_group.update_time
	 * @mbggenerated
	 */
	public String getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_group.update_time
	 * @param updateTime  the value for assistant_group.update_time
	 * @mbggenerated
	 */
	public void setUpdateTime(String updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_group.warm_notice
	 * @return  the value of assistant_group.warm_notice
	 * @mbggenerated
	 */
	public String getWarmNotice() {
		return warmNotice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_group.warm_notice
	 * @param warmNotice  the value for assistant_group.warm_notice
	 * @mbggenerated
	 */
	public void setWarmNotice(String warmNotice) {
		this.warmNotice = warmNotice == null ? null : warmNotice.trim();
	}



	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("id=");
		builder.append(id);
		builder.append(", groupId=");
		builder.append(groupId);
		builder.append(", bizId=");
		builder.append(bizId);
		builder.append(", groupMode=");
		builder.append(groupMode);
		builder.append(", groupCode=");
		builder.append(groupCode);
		builder.append(", productBrandName=");
		builder.append(productBrandName);
		builder.append(", productName=");
		builder.append(productName);
		builder.append(", daynum=");
		builder.append(daynum);
		builder.append(", dateStart=");
		builder.append(dateStart);
		builder.append(", dateEnd=");
		builder.append(dateEnd);
		builder.append(", totalAdult=");
		builder.append(totalAdult);
		builder.append(", totalChild=");
		builder.append(totalChild);
		builder.append(", totalGuide=");
		builder.append(totalGuide);
		builder.append(", operatorName=");
		builder.append(operatorName);
		builder.append(", updateState=");
		builder.append(updateState);
		builder.append(", updateTime=");
		builder.append(updateTime);
		builder.append(", warmNotice=");
		builder.append(warmNotice);
		return builder.toString();
	}

	
    
    
    
}