package com.yimayhd.erpcenter.dal.sales.client.sales.po;

public class AssistantSupplier {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_supplier.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_supplier.supplier_id
	 * @mbggenerated
	 */
	private Integer supplierId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_supplier.supplier_type
	 * @mbggenerated
	 */
	private Integer supplierType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_supplier.name_full
	 * @mbggenerated
	 */
	private String nameFull;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_supplier.name_en
	 * @mbggenerated
	 */
	private String nameEn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_supplier.level
	 * @mbggenerated
	 */
	private String level;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_supplier.province_name
	 * @mbggenerated
	 */
	private String provinceName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_supplier.city_name
	 * @mbggenerated
	 */
	private String cityName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_supplier.area_name
	 * @mbggenerated
	 */
	private String areaName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_supplier.town_name
	 * @mbggenerated
	 */
	private String townName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_supplier.address
	 * @mbggenerated
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_supplier.website
	 * @mbggenerated
	 */
	private String website;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_supplier.position_lon
	 * @mbggenerated
	 */
	private String positionLon;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_supplier.position_lat
	 * @mbggenerated
	 */
	private String positionLat;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_supplier.intro_brief
	 * @mbggenerated
	 */
	private String introBrief;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_supplier.intro_tip
	 * @mbggenerated
	 */
	private String introTip;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_supplier.state
	 * @mbggenerated
	 */
	private Integer state;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_supplier.id
	 * @return  the value of assistant_supplier.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_supplier.id
	 * @param id  the value for assistant_supplier.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_supplier.supplier_id
	 * @return  the value of assistant_supplier.supplier_id
	 * @mbggenerated
	 */
	public Integer getSupplierId() {
		return supplierId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_supplier.supplier_id
	 * @param supplierId  the value for assistant_supplier.supplier_id
	 * @mbggenerated
	 */
	public void setSupplierId(Integer supplierId) {
		this.supplierId = supplierId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_supplier.supplier_type
	 * @return  the value of assistant_supplier.supplier_type
	 * @mbggenerated
	 */
	public Integer getSupplierType() {
		return supplierType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_supplier.supplier_type
	 * @param supplierType  the value for assistant_supplier.supplier_type
	 * @mbggenerated
	 */
	public void setSupplierType(Integer supplierType) {
		this.supplierType = supplierType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_supplier.name_full
	 * @return  the value of assistant_supplier.name_full
	 * @mbggenerated
	 */
	public String getNameFull() {
		return nameFull;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_supplier.name_full
	 * @param nameFull  the value for assistant_supplier.name_full
	 * @mbggenerated
	 */
	public void setNameFull(String nameFull) {
		this.nameFull = nameFull == null ? null : nameFull.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_supplier.name_en
	 * @return  the value of assistant_supplier.name_en
	 * @mbggenerated
	 */
	public String getNameEn() {
		return nameEn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_supplier.name_en
	 * @param nameEn  the value for assistant_supplier.name_en
	 * @mbggenerated
	 */
	public void setNameEn(String nameEn) {
		this.nameEn = nameEn == null ? null : nameEn.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_supplier.level
	 * @return  the value of assistant_supplier.level
	 * @mbggenerated
	 */
	public String getLevel() {
		return level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_supplier.level
	 * @param level  the value for assistant_supplier.level
	 * @mbggenerated
	 */
	public void setLevel(String level) {
		this.level = level == null ? null : level.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_supplier.province_name
	 * @return  the value of assistant_supplier.province_name
	 * @mbggenerated
	 */
	public String getProvinceName() {
		return provinceName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_supplier.province_name
	 * @param provinceName  the value for assistant_supplier.province_name
	 * @mbggenerated
	 */
	public void setProvinceName(String provinceName) {
		this.provinceName = provinceName == null ? null : provinceName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_supplier.city_name
	 * @return  the value of assistant_supplier.city_name
	 * @mbggenerated
	 */
	public String getCityName() {
		return cityName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_supplier.city_name
	 * @param cityName  the value for assistant_supplier.city_name
	 * @mbggenerated
	 */
	public void setCityName(String cityName) {
		this.cityName = cityName == null ? null : cityName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_supplier.area_name
	 * @return  the value of assistant_supplier.area_name
	 * @mbggenerated
	 */
	public String getAreaName() {
		return areaName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_supplier.area_name
	 * @param areaName  the value for assistant_supplier.area_name
	 * @mbggenerated
	 */
	public void setAreaName(String areaName) {
		this.areaName = areaName == null ? null : areaName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_supplier.town_name
	 * @return  the value of assistant_supplier.town_name
	 * @mbggenerated
	 */
	public String getTownName() {
		return townName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_supplier.town_name
	 * @param townName  the value for assistant_supplier.town_name
	 * @mbggenerated
	 */
	public void setTownName(String townName) {
		this.townName = townName == null ? null : townName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_supplier.address
	 * @return  the value of assistant_supplier.address
	 * @mbggenerated
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_supplier.address
	 * @param address  the value for assistant_supplier.address
	 * @mbggenerated
	 */
	public void setAddress(String address) {
		this.address = address == null ? null : address.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_supplier.website
	 * @return  the value of assistant_supplier.website
	 * @mbggenerated
	 */
	public String getWebsite() {
		return website;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_supplier.website
	 * @param website  the value for assistant_supplier.website
	 * @mbggenerated
	 */
	public void setWebsite(String website) {
		this.website = website == null ? null : website.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_supplier.position_lon
	 * @return  the value of assistant_supplier.position_lon
	 * @mbggenerated
	 */
	public String getPositionLon() {
		return positionLon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_supplier.position_lon
	 * @param positionLon  the value for assistant_supplier.position_lon
	 * @mbggenerated
	 */
	public void setPositionLon(String positionLon) {
		this.positionLon = positionLon == null ? null : positionLon.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_supplier.position_lat
	 * @return  the value of assistant_supplier.position_lat
	 * @mbggenerated
	 */
	public String getPositionLat() {
		return positionLat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_supplier.position_lat
	 * @param positionLat  the value for assistant_supplier.position_lat
	 * @mbggenerated
	 */
	public void setPositionLat(String positionLat) {
		this.positionLat = positionLat == null ? null : positionLat.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_supplier.intro_brief
	 * @return  the value of assistant_supplier.intro_brief
	 * @mbggenerated
	 */
	public String getIntroBrief() {
		return introBrief;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_supplier.intro_brief
	 * @param introBrief  the value for assistant_supplier.intro_brief
	 * @mbggenerated
	 */
	public void setIntroBrief(String introBrief) {
		this.introBrief = introBrief == null ? null : introBrief.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_supplier.intro_tip
	 * @return  the value of assistant_supplier.intro_tip
	 * @mbggenerated
	 */
	public String getIntroTip() {
		return introTip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_supplier.intro_tip
	 * @param introTip  the value for assistant_supplier.intro_tip
	 * @mbggenerated
	 */
	public void setIntroTip(String introTip) {
		this.introTip = introTip == null ? null : introTip.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_supplier.state
	 * @return  the value of assistant_supplier.state
	 * @mbggenerated
	 */
	public Integer getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_supplier.state
	 * @param state  the value for assistant_supplier.state
	 * @mbggenerated
	 */
	public void setState(Integer state) {
		this.state = state;
	}
}