package com.yimayhd.erpcenter.dal.sales.client.sales.po;

import java.io.Serializable;

public class AssistantGroupGuide implements Serializable{
	/**
	 * 
	 */
	private static final long serialVersionUID = 6872181579852451199L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_group_guide.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_group_guide.group_id
	 * @mbggenerated
	 */
	private Integer groupId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_group_guide.guide_id
	 * @mbggenerated
	 */
	private Integer guideId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_group_guide.guide_name
	 * @mbggenerated
	 */
	private String guideName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_group_guide.guide_certificate_no
	 * @mbggenerated
	 */
	private Integer guideGender;
	private Integer driverGender;
	private String driverCompany;
	private String guideCertificateNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_group_guide.guide_license_no
	 * @mbggenerated
	 */
	private String guideLicenseNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_group_guide.guide_mobile
	 * @mbggenerated
	 */
	private String guideMobile;
	private String guidePhoto;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_group_guide.driver_id
	 * @mbggenerated
	 */
	private Integer driverId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_group_guide.driver_name
	 * @mbggenerated
	 */
	private String driverName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_group_guide.driver_license_car
	 * @mbggenerated
	 */
	private String driverLicenseCar;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_group_guide.driver_mobile
	 * @mbggenerated
	 */
	private String driverMobile;
	private String driverPhoto;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assistant_group_guide.state
	 * @mbggenerated
	 */
	private Byte state;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_group_guide.id
	 * @return  the value of assistant_group_guide.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_group_guide.id
	 * @param id  the value for assistant_group_guide.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_group_guide.group_id
	 * @return  the value of assistant_group_guide.group_id
	 * @mbggenerated
	 */
	public Integer getGroupId() {
		return groupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_group_guide.group_id
	 * @param groupId  the value for assistant_group_guide.group_id
	 * @mbggenerated
	 */
	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_group_guide.guide_id
	 * @return  the value of assistant_group_guide.guide_id
	 * @mbggenerated
	 */
	public Integer getGuideId() {
		return guideId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_group_guide.guide_id
	 * @param guideId  the value for assistant_group_guide.guide_id
	 * @mbggenerated
	 */
	public void setGuideId(Integer guideId) {
		this.guideId = guideId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_group_guide.guide_name
	 * @return  the value of assistant_group_guide.guide_name
	 * @mbggenerated
	 */
	public String getGuideName() {
		return guideName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_group_guide.guide_name
	 * @param guideName  the value for assistant_group_guide.guide_name
	 * @mbggenerated
	 */
	public void setGuideName(String guideName) {
		this.guideName = guideName == null ? null : guideName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_group_guide.guide_certificate_no
	 * @return  the value of assistant_group_guide.guide_certificate_no
	 * @mbggenerated
	 */
	public String getGuideCertificateNo() {
		return guideCertificateNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_group_guide.guide_certificate_no
	 * @param guideCertificateNo  the value for assistant_group_guide.guide_certificate_no
	 * @mbggenerated
	 */
	public void setGuideCertificateNo(String guideCertificateNo) {
		this.guideCertificateNo = guideCertificateNo == null ? null : guideCertificateNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_group_guide.guide_license_no
	 * @return  the value of assistant_group_guide.guide_license_no
	 * @mbggenerated
	 */
	public String getGuideLicenseNo() {
		return guideLicenseNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_group_guide.guide_license_no
	 * @param guideLicenseNo  the value for assistant_group_guide.guide_license_no
	 * @mbggenerated
	 */
	public void setGuideLicenseNo(String guideLicenseNo) {
		this.guideLicenseNo = guideLicenseNo == null ? null : guideLicenseNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_group_guide.guide_mobile
	 * @return  the value of assistant_group_guide.guide_mobile
	 * @mbggenerated
	 */
	public String getGuideMobile() {
		return guideMobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_group_guide.guide_mobile
	 * @param guideMobile  the value for assistant_group_guide.guide_mobile
	 * @mbggenerated
	 */
	public void setGuideMobile(String guideMobile) {
		this.guideMobile = guideMobile == null ? null : guideMobile.trim();
	}
	
	public String getGuidePhoto() {
		return guidePhoto;
	}
	public void setGuidePhoto(String guidePhoto) {
		this.guidePhoto = guidePhoto == null ? null : guidePhoto.trim();
	}


	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_group_guide.driver_id
	 * @return  the value of assistant_group_guide.driver_id
	 * @mbggenerated
	 */
	public Integer getDriverId() {
		return driverId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_group_guide.driver_id
	 * @param driverId  the value for assistant_group_guide.driver_id
	 * @mbggenerated
	 */
	public void setDriverId(Integer driverId) {
		this.driverId = driverId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_group_guide.driver_name
	 * @return  the value of assistant_group_guide.driver_name
	 * @mbggenerated
	 */
	public String getDriverName() {
		return driverName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_group_guide.driver_name
	 * @param driverName  the value for assistant_group_guide.driver_name
	 * @mbggenerated
	 */
	public void setDriverName(String driverName) {
		this.driverName = driverName == null ? null : driverName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_group_guide.driver_license_car
	 * @return  the value of assistant_group_guide.driver_license_car
	 * @mbggenerated
	 */
	public String getDriverLicenseCar() {
		return driverLicenseCar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_group_guide.driver_license_car
	 * @param driverLicenseCar  the value for assistant_group_guide.driver_license_car
	 * @mbggenerated
	 */
	public void setDriverLicenseCar(String driverLicenseCar) {
		this.driverLicenseCar = driverLicenseCar == null ? null : driverLicenseCar.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_group_guide.driver_mobile
	 * @return  the value of assistant_group_guide.driver_mobile
	 * @mbggenerated
	 */
	public String getDriverMobile() {
		return driverMobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_group_guide.driver_mobile
	 * @param driverMobile  the value for assistant_group_guide.driver_mobile
	 * @mbggenerated
	 */
	public void setDriverMobile(String driverMobile) {
		this.driverMobile = driverMobile == null ? null : driverMobile.trim();
	}

	
	public String getDriverPhoto() {
		return driverPhoto;
	}
	public void setDriverPhoto(String driverPhoto) {
		this.driverPhoto = driverPhoto == null ? null : driverPhoto.trim();
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assistant_group_guide.state
	 * @return  the value of assistant_group_guide.state
	 * @mbggenerated
	 */
	public Byte getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assistant_group_guide.state
	 * @param state  the value for assistant_group_guide.state
	 * @mbggenerated
	 */
	public void setState(Byte state) {
		this.state = state;
	}

	public Integer getGuideGender() {
		return guideGender;
	}

	public void setGuideGender(Integer guideGender) {
		this.guideGender = guideGender;
	}

	public Integer getDriverGender() {
		return driverGender;
	}

	public void setDriverGender(Integer driverGender) {
		this.driverGender = driverGender;
	}

	public String getDriverCompany() {
		return driverCompany;
	}

	public void setDriverCompany(String driverCompany) {
		this.driverCompany = driverCompany;
	}
}