package com.yimayhd.erpcenter.dal.sales.client.sales.po;

import java.io.Serializable;
import java.util.Date;

public class TransferOrderRoute  implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1077291787652180991L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transfer_order_route.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transfer_order_route.order_id
	 * @mbggenerated
	 */
	private Integer orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transfer_order_route.from_order_id
	 * @mbggenerated
	 */
	private Integer fromOrderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transfer_order_route.day_val
	 * @mbggenerated
	 */
	private Integer dayVal;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transfer_order_route.date_val
	 * @mbggenerated
	 */
	private Date dateVal;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transfer_order_route.breakfast
	 * @mbggenerated
	 */
	private String breakfast;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transfer_order_route.lunch
	 * @mbggenerated
	 */
	private String lunch;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transfer_order_route.supper
	 * @mbggenerated
	 */
	private String supper;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transfer_order_route.hotels
	 * @mbggenerated
	 */
	private String hotels;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transfer_order_route.route_desp
	 * @mbggenerated
	 */
	private String routeDesp;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transfer_order_route.id
	 * @return  the value of transfer_order_route.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transfer_order_route.id
	 * @param id  the value for transfer_order_route.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transfer_order_route.order_id
	 * @return  the value of transfer_order_route.order_id
	 * @mbggenerated
	 */
	public Integer getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transfer_order_route.order_id
	 * @param orderId  the value for transfer_order_route.order_id
	 * @mbggenerated
	 */
	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transfer_order_route.from_order_id
	 * @return  the value of transfer_order_route.from_order_id
	 * @mbggenerated
	 */
	public Integer getFromOrderId() {
		return fromOrderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transfer_order_route.from_order_id
	 * @param fromOrderId  the value for transfer_order_route.from_order_id
	 * @mbggenerated
	 */
	public void setFromOrderId(Integer fromOrderId) {
		this.fromOrderId = fromOrderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transfer_order_route.day_val
	 * @return  the value of transfer_order_route.day_val
	 * @mbggenerated
	 */
	public Integer getDayVal() {
		return dayVal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transfer_order_route.day_val
	 * @param dayVal  the value for transfer_order_route.day_val
	 * @mbggenerated
	 */
	public void setDayVal(Integer dayVal) {
		this.dayVal = dayVal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transfer_order_route.date_val
	 * @return  the value of transfer_order_route.date_val
	 * @mbggenerated
	 */
	public Date getDateVal() {
		return dateVal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transfer_order_route.date_val
	 * @param dateVal  the value for transfer_order_route.date_val
	 * @mbggenerated
	 */
	public void setDateVal(Date dateVal) {
		this.dateVal = dateVal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transfer_order_route.breakfast
	 * @return  the value of transfer_order_route.breakfast
	 * @mbggenerated
	 */
	public String getBreakfast() {
		return breakfast;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transfer_order_route.breakfast
	 * @param breakfast  the value for transfer_order_route.breakfast
	 * @mbggenerated
	 */
	public void setBreakfast(String breakfast) {
		this.breakfast = breakfast == null ? null : breakfast.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transfer_order_route.lunch
	 * @return  the value of transfer_order_route.lunch
	 * @mbggenerated
	 */
	public String getLunch() {
		return lunch;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transfer_order_route.lunch
	 * @param lunch  the value for transfer_order_route.lunch
	 * @mbggenerated
	 */
	public void setLunch(String lunch) {
		this.lunch = lunch == null ? null : lunch.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transfer_order_route.supper
	 * @return  the value of transfer_order_route.supper
	 * @mbggenerated
	 */
	public String getSupper() {
		return supper;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transfer_order_route.supper
	 * @param supper  the value for transfer_order_route.supper
	 * @mbggenerated
	 */
	public void setSupper(String supper) {
		this.supper = supper == null ? null : supper.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transfer_order_route.hotels
	 * @return  the value of transfer_order_route.hotels
	 * @mbggenerated
	 */
	public String getHotels() {
		return hotels;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transfer_order_route.hotels
	 * @param hotels  the value for transfer_order_route.hotels
	 * @mbggenerated
	 */
	public void setHotels(String hotels) {
		this.hotels = hotels == null ? null : hotels.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transfer_order_route.route_desp
	 * @return  the value of transfer_order_route.route_desp
	 * @mbggenerated
	 */
	public String getRouteDesp() {
		return routeDesp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transfer_order_route.route_desp
	 * @param routeDesp  the value for transfer_order_route.route_desp
	 * @mbggenerated
	 */
	public void setRouteDesp(String routeDesp) {
		this.routeDesp = routeDesp == null ? null : routeDesp.trim();
	}
}