package com.yimayhd.erpcenter.dal.sales.client.sales.po;

import java.io.Serializable;

public class TransferOrderGuest implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2340452453571786804L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transfer_order_guest.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transfer_order_guest.order_id
	 * @mbggenerated
	 */
	private Integer orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transfer_order_guest.from_order_id
	 * @mbggenerated
	 */
	private Integer fromOrderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transfer_order_guest.from_order_family_id
	 * @mbggenerated
	 */
	private Integer fromOrderFamilyId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transfer_order_guest.name
	 * @mbggenerated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transfer_order_guest.type
	 * @mbggenerated
	 */
	private Integer type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transfer_order_guest.certificate_num
	 * @mbggenerated
	 */
	private String certificateNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transfer_order_guest.gender
	 * @mbggenerated
	 */
	private Integer gender;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transfer_order_guest.mobile
	 * @mbggenerated
	 */
	private String mobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transfer_order_guest.native_place
	 * @mbggenerated
	 */
	private String nativePlace;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transfer_order_guest.age
	 * @mbggenerated
	 */
	private Integer age;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transfer_order_guest.career
	 * @mbggenerated
	 */
	private String career;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transfer_order_guest.is_single_room
	 * @mbggenerated
	 */
	private Integer isSingleRoom;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transfer_order_guest.remark
	 * @mbggenerated
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transfer_order_guest.id
	 * @return  the value of transfer_order_guest.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transfer_order_guest.id
	 * @param id  the value for transfer_order_guest.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transfer_order_guest.order_id
	 * @return  the value of transfer_order_guest.order_id
	 * @mbggenerated
	 */
	public Integer getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transfer_order_guest.order_id
	 * @param orderId  the value for transfer_order_guest.order_id
	 * @mbggenerated
	 */
	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transfer_order_guest.from_order_id
	 * @return  the value of transfer_order_guest.from_order_id
	 * @mbggenerated
	 */
	public Integer getFromOrderId() {
		return fromOrderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transfer_order_guest.from_order_id
	 * @param fromOrderId  the value for transfer_order_guest.from_order_id
	 * @mbggenerated
	 */
	public void setFromOrderId(Integer fromOrderId) {
		this.fromOrderId = fromOrderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transfer_order_guest.from_order_family_id
	 * @return  the value of transfer_order_guest.from_order_family_id
	 * @mbggenerated
	 */
	public Integer getFromOrderFamilyId() {
		return fromOrderFamilyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transfer_order_guest.from_order_family_id
	 * @param fromOrderFamilyId  the value for transfer_order_guest.from_order_family_id
	 * @mbggenerated
	 */
	public void setFromOrderFamilyId(Integer fromOrderFamilyId) {
		this.fromOrderFamilyId = fromOrderFamilyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transfer_order_guest.name
	 * @return  the value of transfer_order_guest.name
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transfer_order_guest.name
	 * @param name  the value for transfer_order_guest.name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transfer_order_guest.type
	 * @return  the value of transfer_order_guest.type
	 * @mbggenerated
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transfer_order_guest.type
	 * @param type  the value for transfer_order_guest.type
	 * @mbggenerated
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transfer_order_guest.certificate_num
	 * @return  the value of transfer_order_guest.certificate_num
	 * @mbggenerated
	 */
	public String getCertificateNum() {
		return certificateNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transfer_order_guest.certificate_num
	 * @param certificateNum  the value for transfer_order_guest.certificate_num
	 * @mbggenerated
	 */
	public void setCertificateNum(String certificateNum) {
		this.certificateNum = certificateNum == null ? null : certificateNum.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transfer_order_guest.gender
	 * @return  the value of transfer_order_guest.gender
	 * @mbggenerated
	 */
	public Integer getGender() {
		return gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transfer_order_guest.gender
	 * @param gender  the value for transfer_order_guest.gender
	 * @mbggenerated
	 */
	public void setGender(Integer gender) {
		this.gender = gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transfer_order_guest.mobile
	 * @return  the value of transfer_order_guest.mobile
	 * @mbggenerated
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transfer_order_guest.mobile
	 * @param mobile  the value for transfer_order_guest.mobile
	 * @mbggenerated
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile == null ? null : mobile.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transfer_order_guest.native_place
	 * @return  the value of transfer_order_guest.native_place
	 * @mbggenerated
	 */
	public String getNativePlace() {
		return nativePlace;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transfer_order_guest.native_place
	 * @param nativePlace  the value for transfer_order_guest.native_place
	 * @mbggenerated
	 */
	public void setNativePlace(String nativePlace) {
		this.nativePlace = nativePlace == null ? null : nativePlace.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transfer_order_guest.age
	 * @return  the value of transfer_order_guest.age
	 * @mbggenerated
	 */
	public Integer getAge() {
		return age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transfer_order_guest.age
	 * @param age  the value for transfer_order_guest.age
	 * @mbggenerated
	 */
	public void setAge(Integer age) {
		this.age = age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transfer_order_guest.career
	 * @return  the value of transfer_order_guest.career
	 * @mbggenerated
	 */
	public String getCareer() {
		return career;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transfer_order_guest.career
	 * @param career  the value for transfer_order_guest.career
	 * @mbggenerated
	 */
	public void setCareer(String career) {
		this.career = career == null ? null : career.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transfer_order_guest.is_single_room
	 * @return  the value of transfer_order_guest.is_single_room
	 * @mbggenerated
	 */
	public Integer getIsSingleRoom() {
		return isSingleRoom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transfer_order_guest.is_single_room
	 * @param isSingleRoom  the value for transfer_order_guest.is_single_room
	 * @mbggenerated
	 */
	public void setIsSingleRoom(Integer isSingleRoom) {
		this.isSingleRoom = isSingleRoom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transfer_order_guest.remark
	 * @return  the value of transfer_order_guest.remark
	 * @mbggenerated
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transfer_order_guest.remark
	 * @param remark  the value for transfer_order_guest.remark
	 * @mbggenerated
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}
}