package com.yimayhd.erpcenter.dal.sales.client.sales.po;

import java.io.Serializable;
import java.math.BigDecimal;

public class TransferOrderPrice implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6827919695667712575L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transfer_order_price.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transfer_order_price.order_id
	 * @mbggenerated
	 */
	private Integer orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transfer_order_price.from_order_id
	 * @mbggenerated
	 */
	private Integer fromOrderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transfer_order_price.item
	 * @mbggenerated
	 */
	private String item;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transfer_order_price.remark
	 * @mbggenerated
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transfer_order_price.price
	 * @mbggenerated
	 */
	private BigDecimal price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transfer_order_price.num_times
	 * @mbggenerated
	 */
	private BigDecimal numTimes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transfer_order_price.num_person
	 * @mbggenerated
	 */
	private BigDecimal numPerson;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column transfer_order_price.total
	 * @mbggenerated
	 */
	private BigDecimal total;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transfer_order_price.id
	 * @return  the value of transfer_order_price.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transfer_order_price.id
	 * @param id  the value for transfer_order_price.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transfer_order_price.order_id
	 * @return  the value of transfer_order_price.order_id
	 * @mbggenerated
	 */
	public Integer getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transfer_order_price.order_id
	 * @param orderId  the value for transfer_order_price.order_id
	 * @mbggenerated
	 */
	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transfer_order_price.from_order_id
	 * @return  the value of transfer_order_price.from_order_id
	 * @mbggenerated
	 */
	public Integer getFromOrderId() {
		return fromOrderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transfer_order_price.from_order_id
	 * @param fromOrderId  the value for transfer_order_price.from_order_id
	 * @mbggenerated
	 */
	public void setFromOrderId(Integer fromOrderId) {
		this.fromOrderId = fromOrderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transfer_order_price.item
	 * @return  the value of transfer_order_price.item
	 * @mbggenerated
	 */
	public String getItem() {
		return item;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transfer_order_price.item
	 * @param item  the value for transfer_order_price.item
	 * @mbggenerated
	 */
	public void setItem(String item) {
		this.item = item == null ? null : item.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transfer_order_price.remark
	 * @return  the value of transfer_order_price.remark
	 * @mbggenerated
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transfer_order_price.remark
	 * @param remark  the value for transfer_order_price.remark
	 * @mbggenerated
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transfer_order_price.price
	 * @return  the value of transfer_order_price.price
	 * @mbggenerated
	 */
	public BigDecimal getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transfer_order_price.price
	 * @param price  the value for transfer_order_price.price
	 * @mbggenerated
	 */
	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transfer_order_price.num_times
	 * @return  the value of transfer_order_price.num_times
	 * @mbggenerated
	 */
	public BigDecimal getNumTimes() {
		return numTimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transfer_order_price.num_times
	 * @param numTimes  the value for transfer_order_price.num_times
	 * @mbggenerated
	 */
	public void setNumTimes(BigDecimal numTimes) {
		this.numTimes = numTimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transfer_order_price.num_person
	 * @return  the value of transfer_order_price.num_person
	 * @mbggenerated
	 */
	public BigDecimal getNumPerson() {
		return numPerson;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transfer_order_price.num_person
	 * @param numPerson  the value for transfer_order_price.num_person
	 * @mbggenerated
	 */
	public void setNumPerson(BigDecimal numPerson) {
		this.numPerson = numPerson;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column transfer_order_price.total
	 * @return  the value of transfer_order_price.total
	 * @mbggenerated
	 */
	public BigDecimal getTotal() {
		return total;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column transfer_order_price.total
	 * @param total  the value for transfer_order_price.total
	 * @mbggenerated
	 */
	public void setTotal(BigDecimal total) {
		this.total = total;
	}
}