package com.yimayhd.erpcenter.dal.product.po;

import java.io.Serializable;
import java.util.Date;

import com.yihg.basic.util.LogFieldAnno;

public class TrafficResLine implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = -1703546699065723155L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column traffic_res_line.id
	 * @mbggenerated
	 */
	@LogFieldAnno(isKey = true)
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column traffic_res_line.res_id
	 * @mbggenerated
	 */
	private Integer resId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column traffic_res_line.class_no
	 * @mbggenerated
	 */
	@LogFieldAnno(description="班次", delOrIns = true)
	private String classNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column traffic_res_line.line_date
	 * @mbggenerated
	 */
	@LogFieldAnno(description="日期", delOrIns = true)
	private String lineDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column traffic_res_line.departure_city
	 * @mbggenerated
	 */
	@LogFieldAnno(description="出发地", delOrIns = true)
	private String departureCity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column traffic_res_line.departure_time
	 * @mbggenerated
	 */
	@LogFieldAnno(description="出发时间", delOrIns = true)
	private String departureTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column traffic_res_line.arrival_city
	 * @mbggenerated
	 */
	@LogFieldAnno(description="到达地", delOrIns = true)
	private String arrivalCity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column traffic_res_line.arrival_time
	 * @mbggenerated
	 */
	@LogFieldAnno(description="到达时间", delOrIns = true)
	private String arrivalTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column traffic_res_line.remark
	 * @mbggenerated
	 */
	@LogFieldAnno(description="备注")
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column traffic_res_line.user_id
	 * @mbggenerated
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column traffic_res_line.user_name
	 * @mbggenerated
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column traffic_res_line.time_create
	 * @mbggenerated
	 */
	private Date timeCreate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column traffic_res_line.time_update
	 * @mbggenerated
	 */
	private Date timeUpdate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column traffic_res_line.id
	 * @return  the value of traffic_res_line.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column traffic_res_line.id
	 * @param id  the value for traffic_res_line.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column traffic_res_line.res_id
	 * @return  the value of traffic_res_line.res_id
	 * @mbggenerated
	 */
	public Integer getResId() {
		return resId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column traffic_res_line.res_id
	 * @param resId  the value for traffic_res_line.res_id
	 * @mbggenerated
	 */
	public void setResId(Integer resId) {
		this.resId = resId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column traffic_res_line.class_no
	 * @return  the value of traffic_res_line.class_no
	 * @mbggenerated
	 */
	public String getClassNo() {
		return classNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column traffic_res_line.class_no
	 * @param classNo  the value for traffic_res_line.class_no
	 * @mbggenerated
	 */
	public void setClassNo(String classNo) {
		this.classNo = classNo == null ? null : classNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column traffic_res_line.line_date
	 * @return  the value of traffic_res_line.line_date
	 * @mbggenerated
	 */
	public String getLineDate() {
		return lineDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column traffic_res_line.line_date
	 * @param lineDate  the value for traffic_res_line.line_date
	 * @mbggenerated
	 */
	public void setLineDate(String lineDate) {
		this.lineDate = lineDate == null ? null : lineDate.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column traffic_res_line.departure_city
	 * @return  the value of traffic_res_line.departure_city
	 * @mbggenerated
	 */
	public String getDepartureCity() {
		return departureCity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column traffic_res_line.departure_city
	 * @param departureCity  the value for traffic_res_line.departure_city
	 * @mbggenerated
	 */
	public void setDepartureCity(String departureCity) {
		this.departureCity = departureCity == null ? null : departureCity.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column traffic_res_line.departure_time
	 * @return  the value of traffic_res_line.departure_time
	 * @mbggenerated
	 */
	public String getDepartureTime() {
		return departureTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column traffic_res_line.departure_time
	 * @param departureTime  the value for traffic_res_line.departure_time
	 * @mbggenerated
	 */
	public void setDepartureTime(String departureTime) {
		this.departureTime = departureTime == null ? null : departureTime.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column traffic_res_line.arrival_city
	 * @return  the value of traffic_res_line.arrival_city
	 * @mbggenerated
	 */
	public String getArrivalCity() {
		return arrivalCity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column traffic_res_line.arrival_city
	 * @param arrivalCity  the value for traffic_res_line.arrival_city
	 * @mbggenerated
	 */
	public void setArrivalCity(String arrivalCity) {
		this.arrivalCity = arrivalCity == null ? null : arrivalCity.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column traffic_res_line.arrival_time
	 * @return  the value of traffic_res_line.arrival_time
	 * @mbggenerated
	 */
	public String getArrivalTime() {
		return arrivalTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column traffic_res_line.arrival_time
	 * @param arrivalTime  the value for traffic_res_line.arrival_time
	 * @mbggenerated
	 */
	public void setArrivalTime(String arrivalTime) {
		this.arrivalTime = arrivalTime == null ? null : arrivalTime.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column traffic_res_line.remark
	 * @return  the value of traffic_res_line.remark
	 * @mbggenerated
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column traffic_res_line.remark
	 * @param remark  the value for traffic_res_line.remark
	 * @mbggenerated
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column traffic_res_line.user_id
	 * @return  the value of traffic_res_line.user_id
	 * @mbggenerated
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column traffic_res_line.user_id
	 * @param userId  the value for traffic_res_line.user_id
	 * @mbggenerated
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column traffic_res_line.user_name
	 * @return  the value of traffic_res_line.user_name
	 * @mbggenerated
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column traffic_res_line.user_name
	 * @param userName  the value for traffic_res_line.user_name
	 * @mbggenerated
	 */
	public void setUserName(String userName) {
		this.userName = userName == null ? null : userName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column traffic_res_line.time_create
	 * @return  the value of traffic_res_line.time_create
	 * @mbggenerated
	 */
	public Date getTimeCreate() {
		return timeCreate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column traffic_res_line.time_create
	 * @param timeCreate  the value for traffic_res_line.time_create
	 * @mbggenerated
	 */
	public void setTimeCreate(Date timeCreate) {
		this.timeCreate = timeCreate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column traffic_res_line.time_update
	 * @return  the value of traffic_res_line.time_update
	 * @mbggenerated
	 */
	public Date getTimeUpdate() {
		return timeUpdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column traffic_res_line.time_update
	 * @param timeUpdate  the value for traffic_res_line.time_update
	 * @mbggenerated
	 */
	public void setTimeUpdate(Date timeUpdate) {
		this.timeUpdate = timeUpdate;
	}
}