package com.yimayhd.erpcenter.dal.product.dao;

import com.yihg.product.po.TrafficResStocklog;

import java.util.List;

public interface TrafficResStocklogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traffic_res_stocklog
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traffic_res_stocklog
     *
     * @mbggenerated
     */
    int insert(TrafficResStocklog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traffic_res_stocklog
     *
     * @mbggenerated
     */
    TrafficResStocklog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traffic_res_stocklog
     *
     * @mbggenerated
     */
    List<TrafficResStocklog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traffic_res_stocklog
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TrafficResStocklog record);
    int updateByOrderId(TrafficResStocklog record);
    
    int updateByAdjustState(TrafficResStocklog record);
    /**
   	 * 复制功能查询TrafficResStocklog
   	 * @param resId
   	 * @return
   	 */
    List<TrafficResStocklog> selectStocklogbyResId(Integer resId);
    
    int insertSelective(TrafficResStocklog record);

}